### ISSUE TITLE
Checklist - folder structure

### ISSUE THREAD

**Issue by ilijapavlovic95** [nexpav/Moto-GP-Qatar#1]
- [ ] azuriraj `README`; napisi korake kako se pokrece program, sta je potrebno instalirati u lokalu itd.
- [ ] slike prebaci u 'images' folder
- [ ] `pajton.py` je fajl koji se pokrece? cemu sluze `app.py` i `Qatar.py` ?  preimenuj glavni fajl da se zove `app.py` umesto `pajton`
- [ ] cemu sluzi `layout.py` fajl?
- [ ] obrisi backup fajlove (npr. pretpostavljam da ti `pajton backup new` ne treba)
